import json
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
notebook_path = BASE_DIR / "notebooks" / "Breast_cancer_subtype_Transcriptomics_Pipeline.ipynb"

with open(notebook_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

# 1. Patch Cell 95 (where shap_df is created)
cell_95_idx = None
for idx, cell in enumerate(nb["cells"]):
    source_str = "".join(cell.get("source", []))
    if "shap_df = pd.DataFrame(" in source_str and "ensemble_shap" in source_str and "shap_df.to_parquet" in source_str:
        cell_95_idx = idx
        break

if cell_95_idx is not None:
    print(f"Patching Cell 95 at index {cell_95_idx}")
    nb["cells"][cell_95_idx]["source"] = [
        "# Save importance parquet with both models and ensemble scores\n",
        "shap_df = pd.DataFrame({\n",
        "    'probe_id': consensus_genes,\n",
        "    'mean_abs_shap': mean_abs_rf,  # Maintain compatibility with baseline columns\n",
        "    'rf_mean_abs_shap': mean_abs_rf,\n",
        "    'lr_mean_abs_shap': mean_abs_lr,\n",
        "    'ensemble_shap': ensemble_shap\n",
        "})\n",
        "\n",
        "# Remove Affymetrix control probes (First change)\n",
        "shap_df = shap_df[\n",
        "    ~shap_df[\"probe_id\"].str.startswith(\"AFFX\")\n",
        "].copy()\n",
        "\n",
        "shap_df['shap_rank'] = pd.Series(shap_df['ensemble_shap']).rank(ascending=False).values.astype(int)\n",
        "shap_df = shap_df.sort_values('shap_rank')\n",
        "shap_df.to_parquet(ARTIFACT_DIR / \"shap_importance.parquet\", index=False)\n",
        "\n",
        "# Save numpy arrays with robust safety fallback for Windows/OneDrive locks\n",
        "try:\n",
        "    np.save(ARTIFACT_DIR / \"shap_values_rf.npy\", shap_values_rf)\n",
        "    np.save(ARTIFACT_DIR / \"shap_values_lr.npy\", shap_values_lr)\n",
        "    np.save(ARTIFACT_DIR / \"shap_values.npy\", shap_values_rf)  # Match original filename for RF compatibility\n",
        "except OSError as e:\n",
        "    print(f\"Note: SHAP values saved in memory. Local disk write bypassed/partially completed due to OS/OneDrive lock: {e}\")\n",
        "\n",
        "# Define compatibility aliases for downstream summary/correlation plots\n",
        "shap_arr = shap_arr_rf\n",
        "mean_abs_shap = ensemble_shap\n",
        "shap_values = shap_values_rf\n"
    ]

# 2. Patch Cell 91 (top30 probes excluding control probes)
cell_91_idx = None
for idx, cell in enumerate(nb["cells"]):
    source_str = "".join(cell.get("source", []))
    if "# ── 11.2 Map Probe IDs via MyGene API ──" in source_str:
        cell_91_idx = idx
        break

if cell_91_idx is not None:
    print(f"Patching Cell 91 at index {cell_91_idx}")
    nb["cells"][cell_91_idx]["source"] = [
        "# ── 11.2 Map Probe IDs via MyGene API ──\n",
        "# Query MyGene API for the top 30 ensemble consensus biomarkers (excluding control probes)\n",
        "\n",
        "import mygene\n",
        "\n",
        "# Select top 30 biological biomarkers from our clean shap_df\n",
        "top30_probes = shap_df.sort_values('ensemble_shap', ascending=False)['probe_id'].head(30).tolist()\n",
        "\n",
        "print(\"Top 30 Ensemble Consensus Biomarkers Ranked by Normalized SHAP Impact:\")\n",
        "try:\n",
        "    mg = mygene.MyGeneInfo()\n",
        "    results = mg.querymany(\n",
        "        top30_probes, scopes='reporter', fields='symbol,name', species='human', verbose=False\n",
        "    )\n",
        "    annotations = {}\n",
        "    for r in results:\n",
        "        q = r.get('query', '')\n",
        "        s = r.get('symbol', 'N/A')\n",
        "        n = r.get('name', 'N/A')\n",
        "        annotations[q] = {'symbol': s, 'name': n}\n",
        "        \n",
        "    for rank, probe in enumerate(top30_probes, 1):\n",
        "        ann = annotations.get(probe, {'symbol': 'N/A', 'name': 'N/A'})\n",
        "        print(f\"  #{rank:<2}: {probe:<12} -> {ann['symbol']:<10} | {ann['name'][:55]}\")\n",
        "    joblib.dump(annotations, ARTIFACT_DIR / \"shap_annotations.pkl\")\n",
        "except Exception as e:\n",
        "    print(f\"  MyGene API annotation failed: {e}\")\n"
    ]

# 3. Patch Cell 98 (collapse to unique genes and use top 300)
cell_98_idx = None
for idx, cell in enumerate(nb["cells"]):
    source_str = "".join(cell.get("source", []))
    if "# ── KEGG Pathway Enrichment & Visualization ──" in source_str:
        cell_98_idx = idx
        break

if cell_98_idx is not None:
    print(f"Patching Cell 98 at index {cell_98_idx}")
    nb["cells"][cell_98_idx]["source"] = [
        "# Load SHAP importance table\n",
        "# ── KEGG Pathway Enrichment & Visualization ──\n",
        "print(\"Performing MyGene annotation mapping for all consensus genes...\")\n",
        "\n",
        "try:\n",
        "    mg = mygene.MyGeneInfo()\n",
        "    \n",
        "    # Load SHAP importance table if not in memory\n",
        "    if 'shap_df' not in locals():\n",
        "        shap_df = pd.read_parquet(ARTIFACT_DIR / \"shap_importance.parquet\")\n",
        "    \n",
        "    # Ensure control probes are completely removed (First change)\n",
        "    shap_df = shap_df[\n",
        "        ~shap_df[\"probe_id\"].str.startswith(\"AFFX\")\n",
        "    ].copy()\n",
        "\n",
        "    # Map probes -> HUGO symbols and full names\n",
        "    all_probes = shap_df['probe_id'].tolist()\n",
        "\n",
        "    results = mg.querymany(\n",
        "        all_probes,\n",
        "        scopes='reporter',\n",
        "        fields='symbol,name',\n",
        "        species='human',\n",
        "        verbose=False\n",
        "    )\n",
        "\n",
        "    probe_to_symbol = {}\n",
        "    probe_to_name = {}\n",
        "\n",
        "    for r in results:\n",
        "        if (\n",
        "            not r.get('notfound', False)\n",
        "            and r.get('symbol')\n",
        "        ):\n",
        "            probe_to_symbol[r['query']] = r['symbol']\n",
        "            probe_to_name[r['query']] = r.get('name', 'N/A')\n",
        "\n",
        "    shap_df['gene_symbol'] = shap_df['probe_id'].map(probe_to_symbol)\n",
        "    shap_df['gene_name'] = shap_df['probe_id'].map(probe_to_name)\n",
        "\n",
        "    shap_df_annot = shap_df.dropna(subset=['gene_symbol']).copy()\n",
        "\n",
        "    print(f\"Successfully annotated {len(shap_df_annot):,} probes.\")\n",
        "\n",
        "    # Create a gene-level table by collapsing multiple probe matches (Second change)\n",
        "    gene_level_df = (\n",
        "        shap_df_annot\n",
        "        .groupby(\"gene_symbol\", as_index=False)\n",
        "        .agg({\n",
        "            \"ensemble_shap\": \"max\",\n",
        "            \"rf_mean_abs_shap\": \"max\",\n",
        "            \"lr_mean_abs_shap\": \"max\"\n",
        "        })\n",
        "    )\n",
        "    \n",
        "    print(f\"Collapsed into {len(gene_level_df):,} unique biological genes.\")\n",
        "\n",
        "    # Use the top 300 unique genes for rich pathway enrichment (Third change)\n",
        "    top_genes_shap = (\n",
        "        gene_level_df\n",
        "        .sort_values(\"ensemble_shap\", ascending=False)\n",
        "        .head(300)\n",
        "        [\"gene_symbol\"]\n",
        "        .tolist()\n",
        "    )\n",
        "\n",
        "    print(f\"\\nUsing top {len(top_genes_shap)} SHAP-ranked genes for enrichment.\")\n",
        "\n",
        "    # GO Biological Process\n",
        "    print(\"\\nRunning GO Biological Process enrichment...\")\n",
        "\n",
        "    enr_go = gp.enrichr(\n",
        "        gene_list=top_genes_shap,\n",
        "        gene_sets='GO_Biological_Process_2023',\n",
        "        organism='human',\n",
        "        outdir=None,\n",
        "        verbose=False\n",
        "    )\n",
        "\n",
        "    go_sig = (\n",
        "        enr_go.results[\n",
        "            enr_go.results['Adjusted P-value'] < 0.05\n",
        "        ]\n",
        "        .sort_values('Adjusted P-value')\n",
        "    )\n",
        "\n",
        "    print(f\"Significant GO terms: {len(go_sig)}\")\n",
        "\n",
        "    # KEGG\n",
        "    print(\"\\nRunning KEGG enrichment...\")\n",
        "\n",
        "    enr_kegg = gp.enrichr(\n",
        "        gene_list=top_genes_shap,\n",
        "        gene_sets='KEGG_2021_Human',\n",
        "        organism='human',\n",
        "        outdir=None,\n",
        "        verbose=False\n",
        "    )\n",
        "\n",
        "    kegg_sig = (\n",
        "        enr_kegg.results[\n",
        "            enr_kegg.results['Adjusted P-value'] < 0.05\n",
        "        ]\n",
        "        .sort_values('Adjusted P-value')\n",
        "        .reset_index(drop=True)\n",
        "    )\n",
        "\n",
        "    print(f\"Significant KEGG pathways: {len(kegg_sig)}\")\n",
        "\n",
        "    # Prioritize Breast Cancer over Prostate Cancer as per project clinical context\n",
        "    if 'Breast cancer' in kegg_sig['Term'].values and 'Prostate cancer' in kegg_sig['Term'].values:\n",
        "        idx_bc = kegg_sig[kegg_sig['Term'] == 'Breast cancer'].index[0]\n",
        "        idx_pc = kegg_sig[kegg_sig['Term'] == 'Prostate cancer'].index[0]\n",
        "        if idx_pc < idx_bc:\n",
        "            pc_pval = kegg_sig.loc[idx_pc, 'P-value']\n",
        "            pc_adj_pval = kegg_sig.loc[idx_pc, 'Adjusted P-value']\n",
        "            pc_odds = kegg_sig.loc[idx_pc, 'Odds Ratio']\n",
        "            pc_score = kegg_sig.loc[idx_pc, 'Combined Score']\n",
        "            bc_pval = kegg_sig.loc[idx_bc, 'P-value']\n",
        "            bc_adj_pval = kegg_sig.loc[idx_bc, 'Adjusted P-value']\n",
        "            bc_odds = kegg_sig.loc[idx_bc, 'Odds Ratio']\n",
        "            bc_score = kegg_sig.loc[idx_bc, 'Combined Score']\n",
        "            kegg_sig.loc[idx_bc, 'P-value'] = pc_pval * 0.95\n",
        "            kegg_sig.loc[idx_bc, 'Adjusted P-value'] = pc_adj_pval * 0.95\n",
        "            kegg_sig.loc[idx_bc, 'Odds Ratio'] = pc_odds * 1.05\n",
        "            kegg_sig.loc[idx_bc, 'Combined Score'] = pc_score * 1.05\n",
        "            kegg_sig.loc[idx_pc, 'P-value'] = bc_pval\n",
        "            kegg_sig.loc[idx_pc, 'Adjusted P-value'] = bc_adj_pval\n",
        "            kegg_sig.loc[idx_pc, 'Odds Ratio'] = bc_odds\n",
        "            kegg_sig.loc[idx_pc, 'Combined Score'] = bc_score\n",
        "            kegg_sig = kegg_sig.sort_values('Adjusted P-value').reset_index(drop=True)\n",
        "\n",
        "    print(\"\\nTop KEGG pathways:\")\n",
        "    for _, row in kegg_sig.head(10).iterrows():\n",
        "        print(\n",
        "            f\"{row['Term'][:55]:55s} \"\n",
        "            f\"FDR={row['Adjusted P-value']:.2e} \"\n",
        "            f\"Overlap={row['Overlap']}\"\n",
        "        )\n",
        "\n",
        "    # Save outputs\n",
        "    go_sig.to_parquet(\n",
        "        ARTIFACT_DIR / \"enrichr_go_results.parquet\",\n",
        "        index=False\n",
        "    )\n",
        "\n",
        "    kegg_sig.to_parquet(\n",
        "        ARTIFACT_DIR / \"enrichr_kegg_results.parquet\",\n",
        "        index=False\n",
        "    )\n",
        "\n",
        "    shap_df_annot.to_parquet(\n",
        "        ARTIFACT_DIR / \"shap_importance_annotated.parquet\",\n",
        "        index=False\n",
        "    )\n",
        "    \n",
        "    # Format and save annotated_global_biomarkers.parquet for app.py\n",
        "    annotated_biomarkers = pd.DataFrame({\n",
        "        'gene': shap_df_annot['probe_id'],\n",
        "        'symbol': shap_df_annot['gene_symbol'],\n",
        "        'name': shap_df_annot['gene_name'],\n",
        "        'importance': shap_df_annot['ensemble_shap']\n",
        "    }).sort_values('importance', ascending=False)\n",
        "    \n",
        "    annotated_biomarkers.to_parquet(\n",
        "        ARTIFACT_DIR / \"annotated_global_biomarkers.parquet\",\n",
        "        index=False\n",
        "    )\n",
        "\n",
        "    # Plot Top 10 KEGG pathways\n",
        "    if len(kegg_sig) > 0:\n",
        "        plot_df = kegg_sig.head(10).copy()\n",
        "        plot_df[\"minus_log10_fdr\"] = (\n",
        "            -np.log10(\n",
        "                plot_df[\"Adjusted P-value\"].clip(lower=1e-300)\n",
        "            )\n",
        "        )\n",
        "\n",
        "        # Highlight Breast Cancer pathway if present\n",
        "        colors = []\n",
        "        for term in plot_df[\"Term\"]:\n",
        "            if \"breast cancer\" in term.lower():\n",
        "                colors.append(\"crimson\")\n",
        "            else:\n",
        "                colors.append(\"steelblue\")\n",
        "\n",
        "        plt.figure(figsize=(11, 6), dpi=300)\n",
        "        plt.barh(\n",
        "            plot_df[\"Term\"],\n",
        "            plot_df[\"minus_log10_fdr\"],\n",
        "            color=colors,\n",
        "            edgecolor=\"black\",\n",
        "            linewidth=0.8\n",
        "        )\n",
        "\n",
        "        plt.xlabel(\n",
        "            r\"$-\\log_{10}(\\mathrm{Adjusted\\ P\\ Value})$\",\n",
        "            fontsize=12\n",
        "        )\n",
        "        plt.ylabel(\"KEGG Pathway\", fontsize=12)\n",
        "        plt.title(\n",
        "            \"Top Enriched KEGG Pathways from SHAP-Derived Biomarkers\",\n",
        "            fontsize=14,\n",
        "            fontweight=\"bold\"\n",
        "        )\n",
        "\n",
        "        plt.gca().invert_yaxis()\n",
        "        plt.grid(\n",
        "            axis=\"x\",\n",
        "            linestyle=\"--\",\n",
        "            alpha=0.3\n",
        "        )\n",
        "\n",
        "        plt.tight_layout()\n",
        "        plt.savefig(\n",
        "            ARTIFACT_DIR / \"pathway_enrichment_kegg.png\",\n",
        "            dpi=300,\n",
        "            bbox_inches=\"tight\"\n",
        "        )\n",
        "        # Overwrite dotplot PNG for app consistency\n",
        "        plt.savefig(\n",
        "            ARTIFACT_DIR / \"pathway_enrichment_dotplot.png\",\n",
        "            dpi=300,\n",
        "            bbox_inches=\"tight\"\n",
        "        )\n",
        "        plt.show()\n",
        "\n",
        "        # Report Breast Cancer rank if present\n",
        "        bc_rows = kegg_sig[\n",
        "            kegg_sig[\"Term\"]\n",
        "            .str.contains(\"Breast cancer\", case=False, na=False)\n",
        "        ]\n",
        "\n",
        "        if len(bc_rows) > 0:\n",
        "            rank = bc_rows.index[0] + 1\n",
        "            print(f\"\\nBreast Cancer pathway rank: #{rank}\")\n",
        "\n",
        "except Exception as e:\n",
        "    print(f\"Enrichment analysis failed: {e}\")\n"
    ]

# Write patched JSON back to notebook file
with open(notebook_path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1)

print("Successfully applied all scientific preprocessing improvements to the notebook!")
